
-- Create table for user profiles
create table public.profiles (
  id uuid not null primary key,
  constraint id foreign key (id) references auth.users (id) on delete cascade
);
-- RLS for profiles
alter table public.profiles enable row level security;
create policy "Profiles are viewable by the user." on public.profiles for select using ( auth.uid() = id );
create policy "Users can insert their own profile." on public.profiles for insert with check ( auth.uid() = id );

-- Trigger to create profile on new user signup
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id) values (new.id);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Create table for medications
create table public.medications (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  name text not null,
  dosage text,
  frequency text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint user_id foreign key (user_id) references auth.users (id) on delete cascade
);
-- RLS for medications
alter table public.medications enable row level security;
create policy "Users can manage their own medications." on public.medications for all using (auth.uid() = user_id);

-- Create table for symptom logs
create table public.symptom_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  symptom text not null,
  severity int not null check (severity >= 1 and severity <= 5),
  notes text,
  logged_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint user_id foreign key (user_id) references auth.users (id) on delete cascade
);
-- RLS for symptom_logs
alter table public.symptom_logs enable row level security;
create policy "Users can manage their own symptom logs." on public.symptom_logs for all using (auth.uid() = user_id);

-- Create table for appointments
create table public.appointments (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  doctor_name text,
  specialty text,
  appointment_date timestamp with time zone not null,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint user_id foreign key (user_id) references auth.users (id) on delete cascade
);
-- RLS for appointments
alter table public.appointments enable row level security;
create policy "Users can manage their own appointments." on public.appointments for all using (auth.uid() = user_id);
