
-- Create table for daily tips
create table public.tips (
  id bigint generated by default as identity primary key,
  content text not null,
  category text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Allow public read access to tips
alter table public.tips enable row level security;
create policy "Tips are viewable by everyone." on public.tips for select using (true);

-- Insert some initial tips into the database
INSERT INTO public.tips (content, category) VALUES
('Recuerda tomar tu medicamento para la tiroides con el estómago vacío, al menos 30-60 minutos antes del desayuno.', 'Medicación'),
('El ejercicio regular, como caminar o nadar, puede ayudar a mejorar tu metabolismo y estado de ánimo.', 'Estilo de vida'),
('Asegúrate de que tu dieta incluya suficiente selenio. Las nueces de Brasil son una excelente fuente.', 'Nutrición'),
('El estrés puede afectar tu función tiroidea. Prueba con 10 minutos de meditación diaria para relajarte.', 'Bienestar mental'),
('Mantén un diario de síntomas para compartir con tu médico. Te ayudará a identificar patrones.', 'Seguimiento'),
('Evita tomar suplementos de calcio o hierro al mismo tiempo que tu levotiroxina, ya que pueden interferir con su absorción.', 'Medicación'),
('Un sueño de calidad es fundamental. Intenta acostarte y levantarte a la misma hora todos los días.', 'Estilo de vida'),
('Limita el consumo de alimentos bociógenos crudos, como el brócoli o la col rizada. Cocinarlos reduce su efecto.', 'Nutrición'),
('Habla abiertamente sobre cómo te sientes. El apoyo de familiares y amigos es muy valioso.', 'Bienestar mental'),
('No ajustes la dosis de tu medicamento por tu cuenta. Consulta siempre a tu endocrinólogo.', 'Medicación'),
('La hidratación es clave. Bebe suficiente agua a lo largo del día para mantenerte energizado.', 'Estilo de vida'),
('Incluye alimentos ricos en antioxidantes como bayas y verduras de hoja verde en tus comidas.', 'Nutrición'),
('La práctica de yoga suave puede ayudar a reducir la rigidez y mejorar la flexibilidad.', 'Estilo de vida'),
('Si te sientes abrumado, busca grupos de apoyo en línea o en tu comunidad. No estás solo.', 'Bienestar mental'),
('Programa tus análisis de sangre de control según las indicaciones de tu médico para asegurar que tu dosis es la correcta.', 'Seguimiento');
